using BlockchainIdentitySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace BlockchainIdentitySystem.Controllers
{
    public class ApiEndPointController : ApiController
    {
        List<Children> children = new List<Children>()
        {
             new Children { id = 001,NotimeSponsored=3, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Orji Meritus", fatherstatus = "2", mothername = "Orji Cynthia", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 002,NotimeSponsored=20, name = "chinwe Chinenye",sponsored=2, charityHome = "mark charity home",picture="https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Female-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Okeke Meritus", fatherstatus = "2", mothername = "Okeke Chike", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Farmer", province="Anambra", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=false, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 003,NotimeSponsored=0, name = "Chizzy Chinenye",sponsored=3, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Mba Meritus", fatherstatus = "2", mothername = "Mba Nne", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788", email="chike@gmail.com", country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu",picture = "https://www.geek.com/wp-content/uploads/2013/10/time-lapse-625x350.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 004,NotimeSponsored=34, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Aronu Meritus", fatherstatus = "2", mothername = "Mba Chinyere", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "http://images.wisegeek.com/passport-photo.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 001,NotimeSponsored=3, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Orji Meritus", fatherstatus = "2", mothername = "Orji Cynthia", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 002,NotimeSponsored=20, name = "chinwe Chinenye",sponsored=2, charityHome = "mark charity home",picture="https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Female-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Okeke Meritus", fatherstatus = "2", mothername = "Okeke Chike", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Farmer", province="Anambra", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=false, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 003,NotimeSponsored=0, name = "Chizzy Chinenye",sponsored=3, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Mba Meritus", fatherstatus = "2", mothername = "Mba Nne", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788", email="chike@gmail.com", country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu",picture = "https://www.geek.com/wp-content/uploads/2013/10/time-lapse-625x350.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 004,NotimeSponsored=34, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Aronu Meritus", fatherstatus = "2", mothername = "Mba Chinyere", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "http://images.wisegeek.com/passport-photo.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 001,NotimeSponsored=3, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Orji Meritus", fatherstatus = "2", mothername = "Orji Cynthia", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 002,NotimeSponsored=20, name = "chinwe Chinenye",sponsored=2, charityHome = "mark charity home",picture="https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Female-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Okeke Meritus", fatherstatus = "2", mothername = "Okeke Chike", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Farmer", province="Anambra", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=false, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 003,NotimeSponsored=0, name = "Chizzy Chinenye",sponsored=3, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Mba Meritus", fatherstatus = "2", mothername = "Mba Nne", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788", email="chike@gmail.com", country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu",picture = "https://www.geek.com/wp-content/uploads/2013/10/time-lapse-625x350.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 004,NotimeSponsored=34, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Aronu Meritus", fatherstatus = "2", mothername = "Mba Chinyere", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "http://images.wisegeek.com/passport-photo.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 004,NotimeSponsored=34, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Aronu Meritus", fatherstatus = "2", mothername = "Mba Chinyere", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "http://images.wisegeek.com/passport-photo.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 001,NotimeSponsored=3, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Orji Meritus", fatherstatus = "2", mothername = "Orji Cynthia", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 002,NotimeSponsored=20, name = "chinwe Chinenye",sponsored=2, charityHome = "mark charity home",picture="https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Female-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Okeke Meritus", fatherstatus = "2", mothername = "Okeke Chike", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Farmer", province="Anambra", picture = "https://www.canada.ca/content/dam/ircc/migration/ircc/english/passport/images/non-acceptable8-eng.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=false, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=false, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 003,NotimeSponsored=0, name = "Chizzy Chinenye",sponsored=3, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "Male", familyInfo = new FamilyInfo { fathername = "Mba Meritus", fatherstatus = "2", mothername = "Mba Nne", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788", email="chike@gmail.com", country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu",picture = "https://www.geek.com/wp-content/uploads/2013/10/time-lapse-625x350.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } },
             new Children { id = 004,NotimeSponsored=34, name = "Chizzy Chinenye",sponsored=1, charityHome = "mark charity home",picture= "https://www.taylorherring.com/blog/wp-content/uploads/2015/03/Archetypal-Male-Face-of-Beauty-embargoed-to-00.01hrs-30.03.15.jpg", gender = "female", familyInfo = new FamilyInfo { fathername = "Aronu Meritus", fatherstatus = "2", mothername = "Mba Chinyere", motherstatus = "2" }, handlerInfo = new HandlerInfo { name = "Chijioke", address = "myaddress", Dob = "mydateOfbirth", gender = "male", phoneNumber = "0808878788",email="chike@gmail.com",country="Nigeria",EducationalLevel="Higher Edu",Occupation="Teacher", province="Enugu", picture = "http://images.wisegeek.com/passport-photo.jpg" }, healthInfo = new HealthInfo {NeedMedAttension=true, height = "5.0", bloodGroup = "B+", Genotype = "AA", medicalIssue = "", medicalIssueDescription = "", medicalTreatmentFee = "" }, schoolInfo = new SchoolInfo {NeedAcaAttension=true, schoolfeeAmount = "200000", classes = "A", level = "primary 1", schoolname = "that school", term = "that term" } }

        };
        public List<Children> GetJsonData()
        {         

            return children;
        }
        public IHttpActionResult GetJsonDataby(int id)
        {
            var child = children.FirstOrDefault((p) => p.id == id);
            if (child == null)
            {   
                return NotFound();
            }
            return Ok(child);
        }
    }
}
